### ISSUE TITLE
todc-select2 does not display correctly when used with todc-bootstrap 3

### ISSUE THREAD

**Issue by acmetech** [todc/todc-select2#11]
The styling of form controls changed with BS3. The issue can be seen here: http://acmetech.github.io/todc-bootstrap-3/css/#forms-controls

![css todc bootstrap](https://f.cloud.github.com/assets/134294/995464/570cfd42-09be-11e3-9f9c-e3b706dc7542.png)

**Comment by todc** [comment]
Thanks for the report. Looks like there's two causes at work:

1) The "form-control" class on the select element should be removed. Is that required by BS3 for any particular reason?
2) BS3 is setting the box-sizing for all elements to "border-box", and the select2 menu needs it to be "content-box". I can update that.

**Comment by acmetech** [comment]
You're welcome.

> 1) The "form-control" class on the select element should be removed. Is that required by BS3 for any particular reason?

This is the class that gets added to all form controls in BS3. A callout could be added to let the user know that they shouldn't add the form-control class to selects.

> 2) BS3 is setting the box-sizing for all elements to "border-box", and the select2 menu needs it to be "content-box". I can update that.

Great, thanks

**Comment by todc** [comment]
Actually I'll just update the select2 css to solve the first issue as well. It'll be cleaner than having special instructions for BS3.

**Comment by acmetech** [comment]
Sounds good. Thanks.

**Comment by acmetech** [comment]
xref: todc/todc-bootstrap#99

**Comment by todc** [comment]
@acmetech: I updated the select2.css file here. My preliminary tests with your BS3 repo look ok. Check it out and let me know how it goes.

**Comment by acmetech** [comment]
@todc, thanks.

The height of `.select2-container-multi .select2-choices .select2-search-field` input looks off in the multiple select, it's 15px. 23px is probably about right. I also needed to update the path for the png and gif files to ../img to work with todc-bootstrap.

Will todc-select2 support height sizing? http://acmetech.github.io/todc-bootstrap-3/css/#forms-control-sizes

**Comment by todc** [comment]
Thanks. I set the height of `.select2-container-multi .select2-choices .select2-search-field input` to 23px which looks better now.

I'm gonna say "no" on the height sizing for now. Once I have some more time to look at cleanly supporting it from select2.css (without adding lots of BS3-specific selectors to select2), I can revisit it. For now I'd say just remove those select menu examples.

**Comment by acmetech** [comment]
> Thanks. I set the height of .select2-container-multi .select2-choices .select2-search-field input to 23px which looks better now.

Thanks

> I'm gonna say "no" on the height sizing for now. Once I have some more time to look at cleanly supporting it from select2.css (without adding lots of BS3-specific selectors to select2), I can revisit it. For now I'd say just remove those select menu examples.

Will do. I'll add a callout as well.

**Comment by acmetech** [comment]
I've updated the docs. I'll open a new issue for supporting the height sizing classes.
