### ISSUE TITLE
Not working with Bootstrap 2.3.0

### ISSUE THREAD

**Issue by acmetech** [todc/todc-select2#3]
select2 does not appear to work with Bootstrap 2.3.0. I haven't had a chance to look into yet. You can see the problem here, http://acmetech.github.com/todc-bootstrap/base-css.html

**Comment by acmetech** [comment]
Looks like it's jQuery 1.9.x. I added the jquery-migrate plugin for testing and it worked fine.

**Comment by todc** [comment]
Thanks for the report. Looks like there were some patches for 1.9 compatibility in the upstream. I'll merge in the latest this weekend and see how it looks.

**Comment by acmetech** [comment]
You're welcome. I'll test with the updated todc-bootstrap once I hear it's working.

**Comment by todc** [comment]
Updated select2.js and select2.css for jquery 1.9.1 compatibility. There's still a bug when using the Custom Matcher feature of select2, but that shouldn't impact our Bootstrap examples. The select2 [demo page](http://todc.github.com/todc-select2/) has been updated with jquery 1.9.1 as well.

**Comment by acmetech** [comment]
Thanks, but I still see the issue with todc-bootstrap with v2.3.0 of Bootstrap. Have a look here, http://acmetech.github.com/todc-bootstrap/base-css.html#forms

**Comment by todc** [comment]
Where are you getting select2.min.js from? Are you minifying it yourself?

**Comment by acmetech** [comment]
Yes, I minified it myself.

**Comment by todc** [comment]
Looks you need to provide a "value" attribute in the select's option elements, e.g.:

```
<select class="g-select span3">
  <option value="Apple">Apple</option>
  <option value="Banana">Banana</option>
  <option value="Orange">Orange</option>
  <option value="Pear">Pear</option>
  <option value="Peach">Peach</option>
</select>`
```

I'll look into updating select2 so that's not required, but in the meantime that should unblock Bootstrap 2.3.0's progress.

**Comment by acmetech** [comment]
Thanks, that did it.
