### ISSUE TITLE
I need some help!

### ISSUE THREAD

**Issue by kennarr** [todc/todc-select2#6]
Hi, can I have this example please? I love it I want to have it so I can study it and create something similar please can you give me the files for this site? all of the files.images,css,js,jquery.etc please please please I love this example and I want to create something like it plesae give me the files for this website.

**Comment by todc** [comment]
All of the files for this project can be checked out from the git repository. The `master` branch contains the core project code, and the `gh-pages` branch contains the documentation and examples. If you can be more specific, I might be able to help further.
