### ISSUE TITLE
Select2 in Tabs of  Bootstap Modal  doing AJAX Call , not working as expected

### ISSUE THREAD

**Issue by venblee** [todc/todc-select2#8]
I have Select2  inside a Bootstrap Tab , inside a Bootstrap Modal (Popup). Everything Looks and loads fine in the modal , the Select2  only accept one character and will display list that has the one character in them as expected , But when I click on it , to enter more characters it does not type new characters in textbox bellow  the select2 box or accept  anything in textbox at all.

![example2](https://f.cloud.github.com/assets/4137329/673193/ca50d564-d8ac-11e2-9ba0-59e983ef6e91.png)

It look like it lost focus or it class. I have ran this in VS 2012 with IE and Chrome with Dev Tools , not errors or warnings  

I am using the latest version of bootstrap and Select2. 

I have work from the following Examples , if you want to replicate 
http://techtoffee.blogspot.com/2013/03/select2-with-aspnet-mvc.html
http://twitter.github.io/bootstrap/javascript.html#modals
http://twitter.github.io/bootstrap/javascript.html#tabs

**Comment by todc** [comment]
This might be better directed at the select2 repository at: https://github.com/ivaynberg/select2

The todc-select2 project only provides new CSS styles for the widget. We're pulling the javascript directly from ivaynberg's repository.

If you provide a working demo of the problem somewhere, I can help take a look.
